import {cleanDisplayName,sameText,gameParts,isOnOrAfterStartDate,parseShowDate,isCompatibleWithRegulationInnings,isFormallyCompletedGame,addGameStats} from "./src/league-core.js";

const API_ORIGIN="https://mlb26.theshow.com";
const PLATFORMS=new Set(["psn","xbl","mlbts","nsw"]);
const LEGACY_LEAGUE_KEY="public-league-v1",LEAGUE_INDEX_KEY="league-index-v1",DEFAULT_LEAGUE_ID="principal",DEFAULT_LEAGUE_NAME="Torneo Reclutas V2",MAX_SNAPSHOT_BYTES=10*1024*1024;
function cors(extra={}){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Accept,Authorization","Vary":"Origin",...extra};}
function json(body,status=200,headers={}){return new Response(JSON.stringify(body),{status,headers:cors({"Content-Type":"application/json; charset=utf-8",...headers})});}
function validUsername(value){return typeof value==="string"&&value.length>0&&value.length<=80;}
function validLeagueId(value){return typeof value==="string"&&/^[a-z0-9][a-z0-9-]{0,62}$/.test(value);}
function leagueKey(id){return `league:${id}`;}
function phaseName(value){return value==="postseason"?"postseason":"regular";}
function emptyStats(){return {batting:[],pitching:[],loadedGameIds:[],failedGameIds:[]};}
function validStats(stats){return stats&&Array.isArray(stats.batting)&&Array.isArray(stats.pitching)&&Array.isArray(stats.loadedGameIds)&&Array.isArray(stats.failedGameIds)&&stats.batting.length<=10000&&stats.pitching.length<=10000;}
function statAccumulator(stats={}){return {batting:new Map(stats.batting||[]),pitching:new Map(stats.pitching||[]),loadedGameIds:new Set(stats.loadedGameIds||[]),failedGameIds:new Set(stats.failedGameIds||[])};}
function serializedStats(acc){return {batting:[...acc.batting.entries()],pitching:[...acc.pitching.entries()],loadedGameIds:[...acc.loadedGameIds],failedGameIds:[...acc.failedGameIds]};}
function bearerToken(request){return (request.headers.get("Authorization")||"").match(/^Bearer\s+(.+)$/i)?.[1]||"";}
function publicAwards(value){if(!Array.isArray(value))return [];return value.slice(0,12).map(award=>({key:String(award?.key||"").slice(0,20),label:String(award?.label||"").slice(0,30),title:String(award?.title||"").slice(0,60),winners:Array.isArray(award?.winners)?award.winners.slice(0,20).map(winner=>({player:String(winner?.player||"").slice(0,100),manager:String(winner?.manager||"").slice(0,100),team:String(winner?.team||"").slice(0,100),value:String(winner?.value||"").slice(0,30)})).filter(winner=>winner.player&&winner.value):[]})).filter(award=>award.key&&award.title&&award.winners.length);}
function publicChampions(value){if(!Array.isArray(value))return [];return value.slice(0,50).map(entry=>({season:String(entry?.season||"").slice(0,100),champion:String(entry?.champion||"").slice(0,100),team:String(entry?.team||"").slice(0,100),runnerUp:String(entry?.runnerUp||"").slice(0,100),result:String(entry?.result||"").slice(0,50),note:String(entry?.note||"").slice(0,300),finalizedAt:String(entry?.finalizedAt||"").slice(0,40),awards:publicAwards(entry?.awards),regularSeasonAwards:publicAwards(entry?.regularSeasonAwards)})).filter(entry=>entry.season&&entry.champion);}
function publicCorrections(value){if(!Array.isArray(value))return [];return value.slice(0,500).map(item=>({id:String(item?.id||"").slice(0,80),phase:phaseName(item?.phase),type:["result","exclude","batting","pitching"].includes(item?.type)?item.type:"",gameKey:String(item?.gameKey||"").slice(0,160),playerKey:String(item?.playerKey||"").slice(0,240),field:String(item?.field||"").slice(0,30),delta:Number(item?.delta||0),homeScore:Number(item?.homeScore??0),awayScore:Number(item?.awayScore??0),reason:String(item?.reason||"").slice(0,300),createdAt:String(item?.createdAt||"").slice(0,40)})).filter(item=>item.id&&item.type&&item.reason&&Number.isFinite(item.delta)&&Number.isFinite(item.homeScore)&&Number.isFinite(item.awayScore)&&(item.type==="exclude"?item.gameKey:item.type==="result"?item.gameKey&&item.homeScore>=0&&item.awayScore>=0&&item.homeScore!==item.awayScore:item.playerKey&&item.field&&Number.isInteger(item.delta)&&item.delta!==0));}
function publicRegularSeason(value){if(!value||typeof value!=="object"||Array.isArray(value))return null;return {closedAt:String(value.closedAt||"").slice(0,40),qualifiers:Array.isArray(value.qualifiers)?value.qualifiers.slice(0,100).map(item=>String(item).slice(0,100)):[],gameKeys:Array.isArray(value.gameKeys)?value.gameKeys.slice(0,5000).map(item=>String(item).slice(0,180)):[],standings:Array.isArray(value.standings)?value.standings.slice(0,100):[],stats:validStats(value.stats)?value.stats:emptyStats(),awards:publicAwards(value.awards)};}
function publicConfig(config={},leagueId=""){return {leagueId,leagueName:String(config.leagueName||"").slice(0,100),username:String(config.username||"").slice(0,100),platform:"psn",seedGameId:String(config.seedGameId||""),myTeam:String(config.myTeam||"").slice(0,100),startDate:String(config.startDate||"").slice(0,20),regulationInnings:Number(config.regulationInnings||5),maxPages:Number(config.maxPages||20),proxyBase:String(config.proxyBase||"").slice(0,300),roster:config.roster&&typeof config.roster==="object"&&!Array.isArray(config.roster)?config.roster:{},phase:phaseName(config.phase),postseasonQualifiers:Array.isArray(config.postseasonQualifiers)?config.postseasonQualifiers.slice(0,100).map(item=>String(item).slice(0,100)):[],regularSeason:publicRegularSeason(config.regularSeason),corrections:publicCorrections(config.corrections),champions:publicChampions(config.champions),finalizedAt:String(config.finalizedAt||"").slice(0,40)||null};}
function validSnapshot(value){return value&&typeof value==="object"&&!Array.isArray(value)&&value.version===1&&Array.isArray(value.participants)&&Array.isArray(value.games)&&validStats(value.stats)&&value.participants.length<=100&&value.games.length<=5000;}
function rosterHas(config,username){const target=cleanDisplayName(username);return Object.entries(config?.roster||{}).some(([key,value])=>{const data=typeof value==="string"?{}:value||{};return sameText(data.username||key,target)||(Array.isArray(data.aliases)&&data.aliases.some(alias=>sameText(alias,target)));})||sameText(config?.username,target);}
function isQualifier(config,username){return phaseName(config?.phase)!=="postseason"||(config.postseasonQualifiers||[]).some(item=>sameText(item,username));}
function rosterMembers(config){return Object.entries(config?.roster||{}).map(([key,value])=>{const data=typeof value==="string"?{team:value}:value||{};return {username:cleanDisplayName(data.username||key),team:cleanDisplayName(data.team||data.teamName),aliases:Array.isArray(data.aliases)?data.aliases.map(cleanDisplayName).filter(Boolean):[]};}).filter(member=>member.username&&member.team);}
function rosterMember(config,username,team=""){
  const members=rosterMembers(config),direct=members.find(member=>sameText(member.username,username)||member.aliases.some(alias=>sameText(alias,username)));
  if(direct)return direct;
  const byTeam=members.filter(member=>team&&sameText(member.team,team));
  return byTeam.length===1?byTeam[0]:null;
}
function reconcileSnapshotRoster(snapshot){
  const members=rosterMembers(snapshot.config),source=Array.isArray(snapshot.participants)?snapshot.participants:[];
  const participants=members.map(member=>{const direct=source.find(item=>sameText(item.username,member.username)||member.aliases.some(alias=>sameText(item.username,alias))),byTeam=source.filter(item=>sameText(item.team,member.team)),previous=direct||(byTeam.length===1?byTeam[0]:null);return {...(previous||{}),username:member.username,team:member.team,platform:"psn",status:previous?.status||"configured"};});
  const games=(snapshot.games||[]).map(game=>{const home=rosterMember(snapshot.config,game.homeUser,game.homeTeam),away=rosterMember(snapshot.config,game.awayUser,game.awayTeam);return {...game,homeUser:home?.username||game.homeUser,awayUser:away?.username||game.awayUser};});
  return {...snapshot,participants,games};
}
function excludedGameKeys(config){return new Set((config?.corrections||[]).filter(item=>item.type==="exclude").map(item=>String(item.gameKey||"")));}
function activeGames(snapshot){const excluded=excludedGameKeys(snapshot?.config);return (snapshot?.games||[]).filter(game=>!excluded.has(String(game.dedupKey||game.uuid||game.id)));}

async function leagueIndex(env){return await env.LEAGUE_STORE.get(LEAGUE_INDEX_KEY,"json")||{version:1,leagues:[]};}
function leagueName(snapshot,id){const name=cleanDisplayName(snapshot?.config?.leagueName);return name||(id===DEFAULT_LEAGUE_ID?DEFAULT_LEAGUE_NAME:id);}
function withLeagueIdentity(snapshot,id){return snapshot?{...snapshot,config:{...(snapshot.config||{}),leagueId:id,leagueName:leagueName(snapshot,id)}}:null;}
function leagueSummary(snapshot,id){const champion=snapshot.config?.champions?.[0]||null;return {id,name:leagueName(snapshot,id),commissioner:snapshot.config?.username||"",phase:phaseName(snapshot.config?.phase),finalizedAt:snapshot.config?.finalizedAt||null,participants:snapshot.participants?.length||0,games:activeGames(snapshot).length,updatedAt:snapshot.publishedAt||snapshot.lastSync||null,champion:champion?{season:champion.season,champion:champion.champion,team:champion.team,runnerUp:champion.runnerUp,result:champion.result,awards:champion.awards||[],regularSeasonAwards:champion.regularSeasonAwards||[]}:null,regularSeasonAwards:snapshot.config?.regularSeason?.awards||[]};}
async function saveLeague(env,id,snapshot){await env.LEAGUE_STORE.put(leagueKey(id),JSON.stringify(snapshot));const index=await leagueIndex(env),summary=leagueSummary(snapshot,id),position=index.leagues.findIndex(item=>item.id===id);if(position>=0)index.leagues[position]=summary;else index.leagues.push(summary);index.leagues.sort((a,b)=>String(b.updatedAt||"").localeCompare(String(a.updatedAt||"")));await env.LEAGUE_STORE.put(LEAGUE_INDEX_KEY,JSON.stringify(index));}
async function getLeague(env,id){const scoped=await env.LEAGUE_STORE.get(leagueKey(id),"json");if(scoped)return withLeagueIdentity(scoped,id);if(id===DEFAULT_LEAGUE_ID)return withLeagueIdentity(await env.LEAGUE_STORE.get(LEGACY_LEAGUE_KEY,"json"),id);return null;}
async function listLeagues(env){const index=await leagueIndex(env),leagues=index.leagues.map(item=>item.id===DEFAULT_LEAGUE_ID&&(!cleanDisplayName(item.name)||["principal","torneo principal"].includes(cleanDisplayName(item.name).toLowerCase()))?{...item,name:DEFAULT_LEAGUE_NAME}:item);if(!leagues.some(item=>item.id===DEFAULT_LEAGUE_ID)){const legacy=await env.LEAGUE_STORE.get(LEGACY_LEAGUE_KEY,"json");if(legacy)leagues.push(leagueSummary(legacy,DEFAULT_LEAGUE_ID));}return {version:1,leagues};}
async function claimedGameUuids(env,currentId){const index=await leagueIndex(env),ids=new Set(index.leagues.map(item=>item.id).filter(id=>id&&id!==currentId));if(currentId!==DEFAULT_LEAGUE_ID&&await env.LEAGUE_STORE.get(LEGACY_LEAGUE_KEY))ids.add(DEFAULT_LEAGUE_ID);const claimed=new Set();for(const id of ids){const snapshot=await getLeague(env,id);for(const game of activeGames(snapshot)){const uuid=cleanDisplayName(game.uuid);if(uuid)claimed.add(uuid);}}return claimed;}
function phaseDateAllowed(lineScore,config){if(phaseName(config?.phase)!=="postseason")return true;const played=parseShowDate(lineScore?.created_at),closed=new Date(config?.regularSeason?.closedAt||0);return Boolean(played&&played.getTime()>closed.getTime());}
async function officialGameLog(records,config,allowHistoricalUsername=false){for(const record of records.slice(0,4)){if(!/^\d+$/.test(String(record?.id||""))||(!rosterHas(config,record?.username)&&!allowHistoricalUsername))continue;const url=new URL(`${API_ORIGIN}/apis/game_log.json`);url.searchParams.set("id",String(record.id));url.searchParams.set("username",cleanDisplayName(record.username));url.searchParams.set("platform","psn");try{const response=await fetch(url.toString(),{headers:{Accept:"application/json"},cf:{cacheEverything:true,cacheTtl:31536000}});if(response.ok){const payload=await response.json(),lineScore=gameParts(payload).lineScore;if(lineScore&&phaseDateAllowed(lineScore,config))return {payload,record};}}catch{}}return null;}
async function refreshLeague(incoming,current,save,claimedUuids=new Set()){
  current=reconcileSnapshotRoster(current);
  if(!validSnapshot(incoming)||!validSnapshot(current))return json({error:"Invalid league snapshot"},400);if(current.config?.finalizedAt)return json({error:"League is finalized"},409);if(incoming.publishedAt&&current.publishedAt&&incoming.publishedAt!==current.publishedAt)return json({error:"League changed during refresh; reload and try again"},409);
  const existingKeys=new Set(current.games.map(game=>String(game.dedupKey||game.uuid||game.id))),existingUuids=new Set(current.games.map(game=>cleanDisplayName(game.uuid)).filter(Boolean));const candidates=incoming.games.filter(game=>!existingKeys.has(String(game.dedupKey||game.uuid||game.id))&&!existingUuids.has(cleanDisplayName(game.uuid)));if(candidates.length>25)return json({error:"Too many new games; refresh again in smaller batches"},413);if(!candidates.length)return json({...current,refresh:{added:0}},200,{"Cache-Control":"no-store"});
  const participants=current.participants.map(item=>({...item})),participantByName=name=>participants.find(item=>sameText(item.username,name)),acc=statAccumulator(current.stats),accepted=[];let crossLeagueRejected=0;
  for(const candidate of candidates){if(claimedUuids.has(cleanDisplayName(candidate.uuid))){crossLeagueRejected++;continue;}const home=participantByName(candidate.homeUser),away=participantByName(candidate.awayUser);if(!home||!away||!isQualifier(current.config,home.username)||!isQualifier(current.config,away.username)||!sameText(home.team,candidate.homeTeam)||!sameText(away.team,candidate.awayTeam))continue;const records=Array.isArray(candidate.apiRecords)&&candidate.apiRecords.length?candidate.apiRecords:[{id:candidate.id,username:candidate.sourceUser}],official=await officialGameLog(records,current.config,Boolean(home.playerId&&away.playerId));if(!official)continue;const {lineScore}=gameParts(official.payload);if(String(lineScore.game_mode||"").toUpperCase()!=="LEAGUE"||!isFormallyCompletedGame(lineScore,current.config.regulationInnings)||!isCompatibleWithRegulationInnings(lineScore,current.config.regulationInnings))continue;const uuid=cleanDisplayName(lineScore.game_uuid);if(!uuid||uuid!==cleanDisplayName(candidate.uuid)||claimedUuids.has(uuid)||existingUuids.has(uuid)||accepted.some(game=>game.uuid===uuid))continue;if((lineScore.home_full_name&&!sameText(lineScore.home_full_name,home.team))||(lineScore.away_full_name&&!sameText(lineScore.away_full_name,away.team)))continue;const homePlayerId=String(lineScore.home_player_id||""),awayPlayerId=String(lineScore.away_player_id||""),homeTeamId=String(lineScore.home_mlb_team_id||""),awayTeamId=String(lineScore.away_mlb_team_id||"");if(!homePlayerId||!awayPlayerId||(home.playerId&&String(home.playerId)!==homePlayerId)||(away.playerId&&String(away.playerId)!==awayPlayerId))continue;if((home.teamId&&String(home.teamId)!==homeTeamId)||(away.teamId&&String(away.teamId)!==awayTeamId))continue;if(participants.some(item=>!sameText(item.username,home.username)&&String(item.playerId||"")===homePlayerId)||participants.some(item=>!sameText(item.username,away.username)&&String(item.playerId||"")===awayPlayerId))continue;const playedAt=lineScore.created_at||candidate.date;if(!isOnOrAfterStartDate(playedAt,current.config.startDate))continue;Object.assign(home,{playerId:homePlayerId,teamId:homeTeamId,status:"verified"});Object.assign(away,{playerId:awayPlayerId,teamId:awayTeamId,status:"verified"});const game={...candidate,id:String(official.record.id),uuid,dedupKey:`uuid:${uuid}`,phase:phaseName(current.config.phase),date:playedAt||candidate.date,homeScore:Number(lineScore.home_runs),awayScore:Number(lineScore.away_runs),homeResult:cleanDisplayName(lineScore.home_display_result).toUpperCase(),awayResult:cleanDisplayName(lineScore.away_display_result).toUpperCase(),ruling:cleanDisplayName(lineScore.ruling||"0"),homePlayerId,awayPlayerId,apiRecords:records.slice(0,4),sourceUser:official.record.username,sourcePlatform:"psn"};accepted.push(game);addGameStats(acc,game,official.payload);}
  if(!accepted.length)return json({...current,refresh:{added:0,rejected:candidates.length,crossLeagueRejected}},200,{"Cache-Control":"no-store"});const now=new Date().toISOString(),snapshot={...current,publishedAt:now,lastSync:now,participants,games:[...current.games,...accepted],stats:serializedStats(acc)};await save(snapshot);return json({...snapshot,refresh:{added:accepted.length,rejected:candidates.length-accepted.length,crossLeagueRejected}},200,{"Cache-Control":"no-store"});
}
async function readSnapshot(request){const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>MAX_SNAPSHOT_BYTES)return {error:json({error:"Snapshot is too large"},413)};try{const value=JSON.parse(raw);return validSnapshot(value)?{value}:{error:json({error:"Invalid league snapshot"},400)};}catch{return {error:json({error:"Invalid JSON"},400)};}}
async function publishScoped(request,env,id){if(!env.LEAGUE_PUBLISH_TOKEN)return json({error:"Publishing secret is not configured"},503);if(bearerToken(request)!==env.LEAGUE_PUBLISH_TOKEN)return json({error:"Unauthorized"},401,{"WWW-Authenticate":"Bearer"});const parsed=await readSnapshot(request);if(parsed.error)return parsed.error;const incoming=parsed.value,now=new Date().toISOString(),snapshot=reconcileSnapshotRoster({version:1,publishedAt:now,lastSync:incoming.lastSync||null,config:publicConfig(incoming.config,id),participants:incoming.participants,games:incoming.games.map(game=>({...game,phase:game.phase||"regular"})),stats:incoming.stats}),claimed=await claimedGameUuids(env,id),conflicts=activeGames(snapshot).map(game=>cleanDisplayName(game.uuid)).filter(uuid=>uuid&&claimed.has(uuid));if(conflicts.length)return json({error:"Uno o más partidos ya pertenecen a otro torneo.",conflicts:[...new Set(conflicts)]},409);await saveLeague(env,id,snapshot);return json({ok:true,id,publishedAt:now,participants:snapshot.participants.length,games:activeGames(snapshot).length});}

export default {async fetch(request,env={}){if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors()});const url=new URL(request.url);try{
  if(!env.LEAGUE_STORE&&(url.pathname.startsWith("/api/league")||url.pathname.startsWith("/api/leagues")))return json({error:"League storage is not configured"},503);
  if(url.pathname==="/api/leagues"){if(request.method!=="GET")return json({error:"Method not allowed"},405,{Allow:"GET, OPTIONS"});return json(await listLeagues(env),200,{"Cache-Control":"no-store"});}
  const scoped=url.pathname.match(/^\/api\/leagues\/([a-z0-9][a-z0-9-]{0,62})(\/refresh)?$/);if(scoped){const id=scoped[1];if(!validLeagueId(id))return json({error:"Invalid league id"},400);if(scoped[2]){if(request.method!=="POST")return json({error:"Method not allowed"},405,{Allow:"POST, OPTIONS"});const current=await getLeague(env,id);if(!current)return json({error:"League has not been published"},404);let incoming;try{incoming=await request.json()}catch{return json({error:"Invalid JSON"},400)}return refreshLeague(incoming,current,snapshot=>saveLeague(env,id,snapshot),await claimedGameUuids(env,id));}if(request.method==="GET"){const snapshot=await getLeague(env,id);return snapshot?json(snapshot,200,{"Cache-Control":"no-store"}):json({error:"League has not been published"},404,{"Cache-Control":"no-store"});}if(request.method==="POST")return publishScoped(request,env,id);return json({error:"Method not allowed"},405,{Allow:"GET, POST, OPTIONS"});}
  if(url.pathname==="/api/league"){if(request.method==="GET"){const snapshot=await getLeague(env,DEFAULT_LEAGUE_ID);return snapshot?json(snapshot,200,{"Cache-Control":"no-store"}):json({error:"League has not been published"},404);}if(request.method==="POST")return publishScoped(request,env,DEFAULT_LEAGUE_ID);return json({error:"Method not allowed"},405,{Allow:"GET, POST, OPTIONS"});}
  if(url.pathname==="/api/league/refresh"){if(request.method!=="POST")return json({error:"Method not allowed"},405,{Allow:"POST, OPTIONS"});const current=await getLeague(env,DEFAULT_LEAGUE_ID);if(!current)return json({error:"League has not been published"},404);let incoming;try{incoming=await request.json()}catch{return json({error:"Invalid JSON"},400)}return refreshLeague(incoming,current,snapshot=>saveLeague(env,DEFAULT_LEAGUE_ID,snapshot),await claimedGameUuids(env,DEFAULT_LEAGUE_ID));}
  if(request.method!=="GET")return json({error:"Method not allowed"},405);
  if(url.pathname==="/api/history"){const username=url.searchParams.get("username")||"",platform=url.searchParams.get("platform")||"",page=Math.max(1,Math.min(200,Number(url.searchParams.get("page")||1)));if(!validUsername(username)||!PLATFORMS.has(platform))return json({error:"Invalid username/platform"},400);const upstream=new URL(`${API_ORIGIN}/apis/game_history.json`);upstream.searchParams.set("username",username);upstream.searchParams.set("platform",platform);upstream.searchParams.set("page",String(page));upstream.searchParams.set("mode","all");return proxy(upstream,60);}
  if(url.pathname==="/api/game-log"){const id=url.searchParams.get("id")||"",username=url.searchParams.get("username")||"",platform=url.searchParams.get("platform")||"";if(!/^\d+$/.test(id)||!validUsername(username)||!PLATFORMS.has(platform))return json({error:"Invalid id/username/platform"},400);const upstream=new URL(`${API_ORIGIN}/apis/game_log.json`);upstream.searchParams.set("id",id);upstream.searchParams.set("username",username);upstream.searchParams.set("platform",platform);return proxy(upstream,86400);}
  return json({ok:true,service:"MLB The Show 26 Custom League proxy",routes:["/api/history","/api/game-log","/api/leagues","/api/leagues/:id","/api/leagues/:id/refresh"]});
}catch(error){return json({error:error?.message||"Proxy error"},502);}}};
async function proxy(upstream,ttl){const response=await fetch(upstream.toString(),{headers:{Accept:"application/json"},cf:{cacheEverything:true,cacheTtl:ttl}});const body=await response.arrayBuffer();return new Response(body,{status:response.status,headers:cors({"Content-Type":response.headers.get("Content-Type")||"application/json","Cache-Control":`public, max-age=${ttl}`})});}
